### ISSUE TITLE
Support running the ansible module without ansible

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#243]
To be able to use test the ansible module with pytest, I want to be able to call the Ansible module without using ansible.

- [x] Figure out what is needed to call the module
- [x] Create a proof of concept with configuring one static IP address on an Ethernet interface with the module but without Ansible
- [x] Document or propose a patch for the library how to do this

```
git clone https://github.com/linux-system-roles/network/
cd network
ipython
connections = [
    {"name": "testeth", "state": "up", "ip": {"address": ["192.0.2.127/24"]}}
]
# TODO Commands
configure_network(connections)  # naming can be different
# RESULT: testeth has ip address 192.0.2.127
```

References:
https://github.com/tyll/nmstate/commit/4447f3e369009601b06d4c3f27b2bf25ccc1ce8b#diff-6b531a9cd456f54d73ad106d72174513R69
